name: Clojure CI
on: [push, pull_request]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: Set up JDK 11
     uses: actions/setup-java@v2
     with:
       java-version: '11'
       distribution: 'adopt'
   - name: Install Leiningen
     run: |
       curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
       chmod +x lein
       sudo mv lein /usr/local/bin/
   - name: Install dependencies
     run: lein deps
   - name: Run tests
     run: lein fig:test
   - name: Format code
     run: lein cljfmt fix
   - name: Lint code
     run: lein clj-kondo
